version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod #Django가 어떤 settings 파일을 사용할지 지정
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 #Docker 컨테이너 실행 시 어떤 명령어로 서버를 띄울지 지정
    volumes:
      - ./backend:/app/backend
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.prod
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

