name: Deploy to EC2

on:
  push:
    branches:
      - dev_6_2_파일분리_완료후_정적리소스처리-2025-05-31
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build React frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
          
       # 1. EC2에 기존 프로젝트 디렉토리가 있으면 삭제(나중에 삭제)    
      - name: Clean old project directory on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: sudo rm -rf /home/ubuntu/django-react-nginx-hjs-distribute

      # 1. EC2에 프로젝트 디렉토리 생성 (최상위 폴더까지만)
      - name: Create remote directory on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: mkdir -p /home/ubuntu/django-react-nginx-hjs-distribute
            
      
      # 2. 코드 EC2로 전송
      - name: Rsync source code to EC2
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/django-react-nginx-hjs-distribute/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.EC2_KEY }}
      
      # ✅ 3. backend 디렉토리에 .env.prod 생성 (코드 업로드 이후)
      - name: Create .env.prod on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: DJANGO_ENV_PROD_CONTENTS
          script: |
            echo "✅ Copying .env.prod files to project"
            cp /home/ubuntu/django_settings/django.env.prod /home/ubuntu/django-react-nginx-hjs-distribute/backend/.env.prod
            echo "✅ Done copying environment files"
                
      # ✅ 4. frontend 디렉토리에서 .env.prod 생성 및 빌드 수행
      - name: Build Vite frontend on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: VITE_ENV_PROD_CONTENTS
          script: |
            echo "✅ Copying .env.prod files to project"
            cp /home/ubuntu/django_settings/react.env.prod /home/ubuntu/django-react-nginx-hjs-distribute/frontend/.env.prod
            echo "✅ Done copying environment files"

      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/django-react-nginx-hjs-distribute
            docker-compose down
            docker-compose up -d --build
